/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gpp;

public class GPPMain {
    
	public static void main(String[] args) {
		
		System.out.println("Bienvenido a GitHub Parser Project");
		
	}
	
}
