/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gpp;

import org.junit.Test;

import gpp.GPPMain;

import static org.junit.Assert.*;

public class GPPMainTest {
    @Test public void testSomeLibraryMethod() {
        GPPMain classUnderTest = new GPPMain();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    
    // Método de test generado en la clase principal
    public boolean someLibraryMethod() {
        return true;
    }
}
